version: '3.8'

services:
  redis:
    image: redis:alpine
    ports:
      # Expose Redis port to host for potential debugging/direct connection
      - "6379:6379"
    volumes:
      # Persist Redis data
      - redis_data:/data
    restart: unless-stopped

  db: # NEW: Postgres Service
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: postgres # Default user
      POSTGRES_PASSWORD: password # Use a more secure password if needed outside local dev
    ports:
      - "5432:5432" # Expose PostgreSQL port to host
    volumes:
      - pgdata:/var/lib/postgresql/data # Persist PostgreSQL data
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      # Map container port 5000 to HOST port 5001
      - "5001:5000"
    volumes:
      # Mount entire project dir; Python path should find 'backend' package
      - .:/app
    working_dir: /app # Ensure commands run from the project root inside container
    env_file:
      - .env # Pass environment variables from .env file
    environment:
      # Set Flask environment for development
      - FLASK_ENV=development
      # Set the audio root relative to WORKDIR inside container
      # Needs to match the volume mount target above
      - AUDIO_ROOT=/app/output
      - PYTHONPATH=/app # Explicitly add project root to path
      # Add DATABASE_URL for local Postgres
      - DATABASE_URL=postgresql://postgres:password@db:5432/app
    # Command to run the Flask dev server (host 0.0.0.0 makes it accessible)
    command: flask --app backend.app:app run --host=0.0.0.0 --port=5000
    depends_on:
      - redis # Ensure Redis is running before backend starts
      - db    # Ensure Postgres is running before backend starts
    restart: unless-stopped

  worker:
    build:
      # Worker uses Dockerfile in backend directory with project-root context
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      # Mount entire project directory for live code reload
      - .:/app
    working_dir: /app # Run from project root
    env_file:
      - .env
    environment:
      - AUDIO_ROOT=/app/output
      - PYTHONPATH=/app # Explicitly add project root to path
      # Add DATABASE_URL for local Postgres
      - DATABASE_URL=postgresql://postgres:password@db:5432/app
    # Command uses backend.celery_app module
    command: celery -A backend.celery_app:celery worker --loglevel=INFO
    depends_on:
      - redis
      - db    # Ensure Postgres is running before worker starts
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      # Map host 5173 to Nginx container port 80
      - "5173:80"
    volumes:
      # **** VOLUME MUST BE COMMENTED OUT FOR STATIC BUILD ****
      # - ./frontend:/app 
      - /app/node_modules # Keep this isolated
    # No command override needed, CMD in Dockerfile is used
    depends_on: 
      - backend
    restart: unless-stopped

volumes:
  # Define the named volume for Redis persistence
  redis_data: 
  pgdata: # NEW: Define the named volume for Postgres data 