"""Add is_deleted for soft deletes on template models

Revision ID: 005d4f159baa
Revises: 5785d26375c7
Create Date: 2025-04-26 00:04:38.349447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '005d4f159baa'
down_revision = '5785d26375c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vo_script_template_categories', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.create_index(op.f('ix_vo_script_template_categories_is_deleted'), 'vo_script_template_categories', ['is_deleted'], unique=False)
    op.add_column('vo_script_template_lines', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.create_index(op.f('ix_vo_script_template_lines_is_deleted'), 'vo_script_template_lines', ['is_deleted'], unique=False)
    op.add_column('vo_script_templates', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.create_index(op.f('ix_vo_script_templates_is_deleted'), 'vo_script_templates', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vo_script_templates_is_deleted'), table_name='vo_script_templates')
    op.drop_column('vo_script_templates', 'is_deleted')
    op.drop_index(op.f('ix_vo_script_template_lines_is_deleted'), table_name='vo_script_template_lines')
    op.drop_column('vo_script_template_lines', 'is_deleted')
    op.drop_index(op.f('ix_vo_script_template_categories_is_deleted'), table_name='vo_script_template_categories')
    op.drop_column('vo_script_template_categories', 'is_deleted')
    # ### end Alembic commands ###
