"""Add is_locked and custom line fields to vo_script_lines

Revision ID: 3ab799233c3c
Revises: f02e0e9ca9d9
Create Date: 2025-04-28 18:20:09.463060

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3ab799233c3c'
down_revision = 'f02e0e9ca9d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vo_script_lines', sa.Column('is_locked', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.alter_column('vo_script_lines', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vo_script_lines', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('vo_script_lines', 'is_locked')
    # ### end Alembic commands ###
