"""Add is_locked and custom line fields to vo_script_lines

Revision ID: 3ab799233c3c
Revises: f02e0e9ca9d9
Create Date: 2025-04-28 18:20:09.463060

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3ab799233c3c'
down_revision = 'f02e0e9ca9d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - adjusted ###
    # Add new columns
    op.add_column('vo_script_lines', sa.Column('category_id', sa.Integer(), nullable=True))
    op.add_column('vo_script_lines', sa.Column('line_key', sa.String(), nullable=True))
    op.add_column('vo_script_lines', sa.Column('order_index', sa.Integer(), nullable=True))
    op.add_column('vo_script_lines', sa.Column('prompt_hint', sa.Text(), nullable=True))
    # op.add_column('vo_script_lines', sa.Column('is_locked', sa.Boolean(), server_default=sa.text('false'), nullable=False)) # COMMENT OUT - Already exists
    
    # Add foreign key constraint for category_id
    op.create_foreign_key(op.f('fk_vo_script_lines_category_id_vo_script_template_categories'), 'vo_script_lines', 'vo_script_template_categories', ['category_id'], ['id'])
    
    # Make template_line_id nullable
    op.alter_column('vo_script_lines', 'template_line_id',
               existing_type=sa.INTEGER(),
               nullable=True)
               
    # Re-applying with nullable=False based on model def
    op.alter_column('vo_script_lines', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - adjusted ###
    op.alter_column('vo_script_lines', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False, # Revert based on previous state? Needs check.
               existing_server_default=sa.text('now()'))
               
    # Revert template_line_id nullability
    op.alter_column('vo_script_lines', 'template_line_id',
               existing_type=sa.INTEGER(),
               nullable=False) # Revert to NOT NULL
               
    # Drop foreign key constraint - COMMENT OUT as it might not exist if first upgrade failed
    # op.drop_constraint(op.f('fk_vo_script_lines_category_id_vo_script_template_categories'), 'vo_script_lines', type_='foreignkey')
    
    # Drop added columns - COMMENT OUT as they might not exist if first upgrade failed
    # op.drop_column('vo_script_lines', 'is_locked') # UNCOMMENT - This column likely exists
    # op.drop_column('vo_script_lines', 'prompt_hint')
    # op.drop_column('vo_script_lines', 'order_index')
    # op.drop_column('vo_script_lines', 'line_key')
    # op.drop_column('vo_script_lines', 'category_id')
    # ### end Alembic commands ###
