"""Add is_locked and custom line fields to vo_script_lines

Revision ID: 3ab799233c3c
Revises: f02e0e9ca9d9
Create Date: 2025-04-28 18:20:09.463060

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3ab799233c3c'
down_revision = 'f02e0e9ca9d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - adjusted ###
    # Add new columns
    op.add_column('vo_script_lines', sa.Column('category_id', sa.Integer(), nullable=True))
    op.add_column('vo_script_lines', sa.Column('line_key', sa.String(), nullable=True))
    op.add_column('vo_script_lines', sa.Column('order_index', sa.Integer(), nullable=True))
    op.add_column('vo_script_lines', sa.Column('prompt_hint', sa.Text(), nullable=True))
    op.add_column('vo_script_lines', sa.Column('is_locked', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    
    # Add foreign key constraint for category_id
    op.create_foreign_key(op.f('fk_vo_script_lines_category_id_vo_script_template_categories'), 'vo_script_lines', 'vo_script_template_categories', ['category_id'], ['id'])
    
    # Make template_line_id nullable
    op.alter_column('vo_script_lines', 'template_line_id',
               existing_type=sa.INTEGER(),
               nullable=True)
               
    # Re-applying with nullable=False based on model def
    op.alter_column('vo_script_lines', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - adjusted ###
    # For the downgrade to be symmetrical, we should also ensure we try to drop is_locked.
    # However, the other commented out drop_columns might also need review if they were conditionally added.
    # For now, focusing on is_locked as it's the current blocker.
    # op.drop_column('vo_script_lines', 'is_locked') # Temporarily comment out for this fix
    
    op.alter_column('vo_script_lines', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
               
    op.alter_column('vo_script_lines', 'template_line_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    
    # If the foreign key was created in upgrade, it should be dropped in downgrade.
    # Assuming it might not have been created if a previous upgrade attempt failed partially, 
    # it's safer to attempt to drop it if it exists. Or, if the create_foreign_key is robust to pre-existence.
    # For now, let's assume we need to drop it if it was created.
    # op.drop_constraint(op.f('fk_vo_script_lines_category_id_vo_script_template_categories'), 'vo_script_lines', type_='foreignkey') # Keep commented if unsure
    
    # Drop other columns if they were definitely added by this migration's upgrade path
    op.drop_column('vo_script_lines', 'prompt_hint')
    op.drop_column('vo_script_lines', 'order_index')
    op.drop_column('vo_script_lines', 'line_key')
    op.drop_column('vo_script_lines', 'category_id')
    # ### end Alembic commands ###
