"""Add VO Script Creator tables

Revision ID: 5785d26375c7
Revises: 41043f7059ce
Create Date: 2025-04-25 14:31:34.844803

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5785d26375c7'
down_revision = '41043f7059ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vo_script_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('prompt_hint', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vo_script_templates_name'), 'vo_script_templates', ['name'], unique=True)
    op.create_table('vo_script_template_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('prompt_instructions', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['vo_script_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vo_script_template_categories_template_id'), 'vo_script_template_categories', ['template_id'], unique=False)
    op.create_index('uq_category_template_name', 'vo_script_template_categories', ['template_id', 'name'], unique=True)
    op.create_table('vo_scripts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('character_description', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['vo_script_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vo_scripts_name'), 'vo_scripts', ['name'], unique=False)
    op.create_index(op.f('ix_vo_scripts_status'), 'vo_scripts', ['status'], unique=False)
    op.create_index(op.f('ix_vo_scripts_template_id'), 'vo_scripts', ['template_id'], unique=False)
    op.create_table('vo_script_template_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('line_key', sa.String(length=255), nullable=False),
    sa.Column('prompt_hint', sa.Text(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['vo_script_template_categories.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['vo_script_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vo_script_template_lines_category_id'), 'vo_script_template_lines', ['category_id'], unique=False)
    op.create_index(op.f('ix_vo_script_template_lines_template_id'), 'vo_script_template_lines', ['template_id'], unique=False)
    op.create_index('uq_template_line_key', 'vo_script_template_lines', ['template_id', 'line_key'], unique=True)
    op.create_table('vo_script_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vo_script_id', sa.Integer(), nullable=False),
    sa.Column('template_line_id', sa.Integer(), nullable=False),
    sa.Column('generated_text', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('generation_history', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('latest_feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['template_line_id'], ['vo_script_template_lines.id'], ),
    sa.ForeignKeyConstraint(['vo_script_id'], ['vo_scripts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vo_script_lines_status'), 'vo_script_lines', ['status'], unique=False)
    op.create_index(op.f('ix_vo_script_lines_template_line_id'), 'vo_script_lines', ['template_line_id'], unique=False)
    op.create_index(op.f('ix_vo_script_lines_vo_script_id'), 'vo_script_lines', ['vo_script_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vo_script_lines_vo_script_id'), table_name='vo_script_lines')
    op.drop_index(op.f('ix_vo_script_lines_template_line_id'), table_name='vo_script_lines')
    op.drop_index(op.f('ix_vo_script_lines_status'), table_name='vo_script_lines')
    op.drop_table('vo_script_lines')
    op.drop_index('uq_template_line_key', table_name='vo_script_template_lines')
    op.drop_index(op.f('ix_vo_script_template_lines_template_id'), table_name='vo_script_template_lines')
    op.drop_index(op.f('ix_vo_script_template_lines_category_id'), table_name='vo_script_template_lines')
    op.drop_table('vo_script_template_lines')
    op.drop_index(op.f('ix_vo_scripts_template_id'), table_name='vo_scripts')
    op.drop_index(op.f('ix_vo_scripts_status'), table_name='vo_scripts')
    op.drop_index(op.f('ix_vo_scripts_name'), table_name='vo_scripts')
    op.drop_table('vo_scripts')
    op.drop_index('uq_category_template_name', table_name='vo_script_template_categories')
    op.drop_index(op.f('ix_vo_script_template_categories_template_id'), table_name='vo_script_template_categories')
    op.drop_table('vo_script_template_categories')
    op.drop_index(op.f('ix_vo_script_templates_name'), table_name='vo_script_templates')
    op.drop_table('vo_script_templates')
    # ### end Alembic commands ###
