"""Add ScriptNote table for AI collaborator chat

Revision ID: a749aa0ad3a8
Revises: 734db99a3f4e
Create Date: 2025-05-07 00:14:23.585417

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a749aa0ad3a8'
down_revision = '734db99a3f4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('script_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vo_script_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('line_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('text_content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['vo_script_template_categories.id'], ),
    sa.ForeignKeyConstraint(['line_id'], ['vo_script_lines.id'], ),
    sa.ForeignKeyConstraint(['vo_script_id'], ['vo_scripts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_script_notes_category_id'), 'script_notes', ['category_id'], unique=False)
    op.create_index(op.f('ix_script_notes_id'), 'script_notes', ['id'], unique=False)
    op.create_index(op.f('ix_script_notes_line_id'), 'script_notes', ['line_id'], unique=False)
    op.create_index(op.f('ix_script_notes_vo_script_id'), 'script_notes', ['vo_script_id'], unique=False)
    op.alter_column('vo_script_lines', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_vo_script_lines_category_id'), 'vo_script_lines', ['category_id'], unique=False)
    op.alter_column('vo_script_template_lines', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('vo_script_template_lines', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_vo_script_template_lines_is_deleted', table_name='vo_script_template_lines')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_vo_script_template_lines_is_deleted', 'vo_script_template_lines', ['is_deleted'], unique=False)
    op.alter_column('vo_script_template_lines', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('vo_script_template_lines', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_vo_script_lines_category_id'), table_name='vo_script_lines')
    op.alter_column('vo_script_lines', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_script_notes_vo_script_id'), table_name='script_notes')
    op.drop_index(op.f('ix_script_notes_line_id'), table_name='script_notes')
    op.drop_index(op.f('ix_script_notes_id'), table_name='script_notes')
    op.drop_index(op.f('ix_script_notes_category_id'), table_name='script_notes')
    op.drop_table('script_notes')
    # ### end Alembic commands ###
