"""Add chat_message_history table

Revision ID: ad0e9c4bd23d
Revises: a749aa0ad3a8
Create Date: 2025-05-07 14:54:09.749417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad0e9c4bd23d'
down_revision = 'a749aa0ad3a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_message_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vo_script_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vo_script_id'], ['vo_scripts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_message_history_id'), 'chat_message_history', ['id'], unique=False)
    op.create_index(op.f('ix_chat_message_history_timestamp'), 'chat_message_history', ['timestamp'], unique=False)
    op.create_index(op.f('ix_chat_message_history_vo_script_id'), 'chat_message_history', ['vo_script_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_message_history_vo_script_id'), table_name='chat_message_history')
    op.drop_index(op.f('ix_chat_message_history_timestamp'), table_name='chat_message_history')
    op.drop_index(op.f('ix_chat_message_history_id'), table_name='chat_message_history')
    op.drop_table('chat_message_history')
    # ### end Alembic commands ###
