"""Add refinement_prompt columns to VoScript and Category

Revision ID: f02e0e9ca9d9
Revises: aae67b8739de # Should be the ID of the previous migration
Create Date: <timestamp>

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f02e0e9ca9d9'
down_revision: Union[str, None] = 'aae67b8739de' # Check this ID
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vo_script_template_categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('refinement_prompt', sa.Text(), nullable=True))

    with op.batch_alter_table('vo_scripts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('refinement_prompt', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vo_scripts', schema=None) as batch_op:
        batch_op.drop_column('refinement_prompt')

    with op.batch_alter_table('vo_script_template_categories', schema=None) as batch_op:
        batch_op.drop_column('refinement_prompt')
    # ### end Alembic commands ###
